insert into Accounts (LOGIN, ACTIVE, PASSWORD, ROLE,address, name, patronymic, phone, surname,balance, discount) values ('admin', 1, 'admin123', 'ADMIN','test address', 'test name', 'test patronymic', 'test phone', 'test surname',2000, 5);
insert into Accounts (LOGIN, ACTIVE, PASSWORD, ROLE,address, name, patronymic, phone, surname,balance, discount) values ('user', 1, 'user123', 'CUSTOMER','test address', 'test name', 'test patronymic', 'test phone', 'test surname',2000, 5);
insert into Accounts (LOGIN, ACTIVE, PASSWORD, ROLE,address, name, patronymic, phone, surname,balance, discount) values ('user2', 1, 'user123', 'CUSTOMER','test address', 'test name', 'test patronymic', 'test phone', 'test surname',2000, 5);
insert into FLOWERS (NAME, PRICE,quantity) values ('Red rose', 1.40,413);
insert into FLOWERS(NAME, PRICE,quantity) VALUES ( 'Violes', 0.5 ,241);
insert into FLOWERS (NAME, PRICE,quantity) values ('Black rose', 2.10,363);
insert into FLOWERS(NAME, PRICE,quantity) VALUES ( 'White rose', 1.95,537 );
insert into FLOWERS (NAME, PRICE,quantity) values ('Rainbow rose', 2.00,675);
insert into FLOWERS(NAME, PRICE,quantity) VALUES ( 'Pink rose', 1.3,568 );
insert into FLOWERS(NAME, PRICE,quantity) values ( 'White lilium', 2.25,345 );
insert into FLOWERS(NAME, PRICE,quantity) values ( 'Yellow lilium', 2.25,764 );
insert into FLOWERS(NAME, PRICE,quantity) values ( 'Pink lilium', 2.25,765 );
insert into FLOWERS(NAME, PRICE,quantity) values ( 'Lowa rose white lilium', 2.25,567 );
insert into FLOWERS(NAME, PRICE,quantity) values ( 'Lowa rose black lilium', 2.25,567 );